### ISSUE TITLE
Invalid CEN header + cannot see "Libraries in scope" dialog

### ISSUE THREAD

**Issue by Michadelic** [vobujs/ui5-codecompletion#2]
Hi @vobujs,

wonderful idea to provide code completion for webstorm, i just tried to get it working for my installation (Webstorm 2016.3.4) but i do not get this dialog. The dialog ends with the "Power save" checkbox.

I also got an error when executing the install command but i am not sure whether it is related:
"openui5-worklist-app>ui5-codecompletion install
downloading https://openui5.hana.ondemand.com/downloads/openui5-runtime-1.44.19.zip
   [====================] 2060880/bps 100% 0.0s
extracting UI5 sources to openui5-worklist-app\.ui5...
Invalid CEN header (bad signature)"

Any idea where this setting is hidden in the latest version?
https://github.com/vobujs/ui5-codecompletion/blob/develop/doc/ws-scope.png

Kind Regards,
Michael

**Comment by vobujs** [comment]
this looks like an error in the script, not in WebStorm; specifically the source path to extract the .zip to.
In the script, this is provided via `path.join(process.cwd(), '.ui5')` - in your case this doesn't seem to work properly.
What OS are you on?

**Comment by Michadelic** [comment]
Windoof 10

**Comment by Michadelic** [comment]
PS: my path is C:\Users\<Username>\git\openui5

**Comment by vobujs** [comment]
`process.cwd()` should then have returned `C:\\Users\\<Username>\\git\\openui5\\openui5-worklist-app` which it obviously hasn't.
Powershell or cmd?
Either way: could you please cd to your dir, issue `node` and then `process.cwd()` for me please?

**Comment by Michadelic** [comment]
seems ok:

C:\Users\FluffyCat666\git\openui5>node
> process.cwd()
'C:\\Users\\FluffyCat666\\git\\openui5'
>

**Comment by vobujs** [comment]
grmpf. let me find a Win machine and check what's going on...will report back here.

**Comment by vobujs** [comment]
so, hate to say it, but "it works here":
```
C:\Users\Volker Buzek\test>ui5-codecompletion install
downloading https://openui5.hana.ondemand.com/downloads/openui5-runtime-1.44.19.zip
   [====================] 7680116/bps 100% 0.0s
extracting UI5 sources to C:\Users\Volker Buzek\test\.ui5...
   ...done!
deleting .zip: done!
providing code completion from
   C:\Users\Volker Buzek\test\.ui5\resources
for 1381 files (*dbg.js only).
adding UI5-sources to 0 already existing 'Libraries in Scope'.
fallbackfile undefined does not exist
********************************************************************************
HINT: you might want to add
   C:\Users\Volker Buzek\test\.ui5
to .gitignore (or your VCS's equivalent)
in order to avoid adding the UI5 sources to version control
********************************************************************************
```
What version of node are you on?
On my Win10 machine: 6.11.3 (LTS)

**Comment by Michadelic** [comment]
seemed like a node issue, i had version 6.10 installed and updated to the latest one, now it worked fine
