### ISSUE TITLE
Invalid or unsupported zip format. No END header found

### ISSUE THREAD

**Issue by Raptor05** [vobujs/ui5-codecompletion#4]
Dear developers,

I have found a problem with the NPM package. The first step "npm install -g ui5-codecompletion" is still working. However, when I execute the "ui5-codecompletion install" command described in Usage, I get the following error:

> downloading https://openui5.hana.ondemand.com/downloads/openui5-runtime-1.44.19.zip
>    [====================] 131000/bps 100% 0.0s
> extracting UI5 sources to C:\<path>\Workspace\Webstorm\<Project>\.ui5...
> Invalid or unsupported zip format. No END header found

Is that a known problem? How can I solve this? 

Thanks a lot!

Kind regards,
Mark

**Comment by vobujs** [comment]
Hi Mark,
this typically happens when the CLI can't download the file from the provided (or default) URL - then the zip-utility encounters an empty zip and reports "no END header found".
You behind a corporate firewall by any chance?
If so, make sure you have your environment variables configured correctly for proxy usage:
```
# Win
set HTTP_PROXY="http://proxy:8080"
set HTTPS_PROXY="http://proxy:8080"
# Nix, e.g. bash
export HTTP_PROXY="http://proxy:8080"
export HTTPS_PROXY="http://proxy:8080"
```
the CLI picks up the proxy setting from your environment variables, then should be able to download the .zip

HTH, v.

**Comment by Raptor05** [comment]
Hey,

Normally I'm behind a corporate firewall and use a proxy, but I've deactivated it and now access the Internet via UMTS, without firewall and proxy.
The archive in the directory "...\AppData\Roaming\npm-cache\ui5-codecompletion\1.0.4" is also not empty, there are some folders like bin, doc, lib etc. underneath it. Nevertheless, I still get this error.

**Comment by vobujs** [comment]
when you deactivated the proxy, did you also delete the HTTP(S)_PROXY environment variables?
to check, in cmd or PowerShell:
```
echo %HTTP_PROXY%
echo %HTTPS_PROXY%
```
and/or is the proxy also set on node-level?
to check, in cmd or PowerShell:
```
npm config get proxy
npm config get https-proxy
```

**Comment by Raptor05** [comment]
They are both deactivated.

1. echo %HTTP_PROXY% returns %HTTP_PROXY%

2. npm config get proxy returns null

https the same.

**Comment by vobujs** [comment]
hm, is there anything downloaded at all to:
C:<path>\Workspace\Webstorm<Project>\.ui5
?
If yes, can you manually unzip the file?

**Comment by Raptor05** [comment]
Nope, the folder is completely empty.
Is there a chance to fix it when I reinstall the whole Webstorm IDE?

**Comment by vobujs** [comment]
URGH, I found the issue:
https://openui5.hana.ondemand.com/downloads/openui5-runtime-1.44.19.zip
is not available any more! The latest minor release seems to be .21.
I'll update ```ui5-codecompletion``` immediately...
Meanwhile you can specify a URL to download from via the ```-f```switch:
```
ui5-codecompletion -f=https://openui5.hana.ondemand.com/downloads/openui5-runtime-1.44.21.zip
```

**Comment by Raptor05** [comment]
Oh okay, thanks a lot!
It reassures me to hear it's not a problem with my machine :)

**Comment by vobujs** [comment]
please update your ```ui5-codecompletion``` installation and try again

**Comment by Raptor05** [comment]
The execution of the command 
`ui5-codecompletion install`
still leads to an error. But with 
`ui5-codecompletion install -f=https://openui5.hana.ondemand.com/downloads/openui5-runtime-1.44.21.zip`
it seems to work at a first view. It downloads something. But after this I get another error:
`Invalid CEN header (bad signature)`

**Comment by vobujs** [comment]
hm, can't reproduce. 
just tested myself:
```
box> ~/git/ui5-codecompletion > ui5-codecompletion install
downloading https://openui5.hana.ondemand.com/downloads/openui5-runtime-1.44.21.zip
   [====================] 40016700/bps 100% 0.0s
extracting UI5 sources to /bla/fasel/ui5-codecompletion/.ui5...
   ...done!
deleting .zip: done!
providing code completion from 
   .ui5/resources 
for 1381 files (*dbg.js only).
adding UI5-sources to 1 already existing 'Libraries in Scope'.
********************************************************************************
HINT: you might want to add 
   /bla/fasel/ui5-codecompletion/.ui5 
to .gitignore (or your VCS's equivalent)
in order to avoid adding the UI5 sources to version control
********************************************************************************
```

**Comment by vobujs** [comment]
probably a node version issue? 
/me running node 8.7.0 - what are you on?

**Comment by Raptor05** [comment]
I'm on version 6.11.2, I just try to install the newest release and will get back then.

**Comment by Raptor05** [comment]
I still get the same error

```
C:\<path>\Workspace\Webstorm\<project>>npm install -g ui5-codecompletion
C:\Users\<user>\AppData\Roaming\npm\ui5-codecompletion -> C:\Users\<user>\AppData\Roaming\npm\node_modules\ui5-codecompletion\bin\index.js
+ ui5-codecompletion@1.0.5
added 116 packages in 15.061s

C:\<path>\Workspace\Webstorm\<project>>ui5-codecompletion install
downloading https://openui5.hana.ondemand.com/downloads/openui5-runtime-1.44.21.zip
   [====================] 1415866/bps 100% 0.0s
extracting UI5 sources to C:\<path>\Workspace\Webstorm\<project>\.ui5...
Invalid CEN header (bad signature)
```

The .ui5 folder is empty after the execution.

I've found some error log file in the project folder (npm-debug.log):

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ui5-codecompletion' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData ui5-codecompletion
8 silly fetchNamedPackageData ui5-codecompletion
9 silly mapToRegistry name ui5-codecompletion
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'ui5-codecompletion',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'ui5-codecompletion',
12 silly mapToRegistry   name: 'ui5-codecompletion',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/ui5-codecompletion
14 verbose request uri https://registry.npmjs.org/ui5-codecompletion
15 verbose request no auth needed
16 info attempt registry request try #1 at 08:24:46
17 verbose request id b57963a3c80a131a
18 verbose etag W/"59b2fd13-398c"
19 verbose lastModified Fri, 08 Sep 2017 20:26:59 GMT
20 http request GET https://registry.npmjs.org/ui5-codecompletion
21 verbose stack Error: kill ENOSYS
21 verbose stack     at exports._errnoException (util.js:1020:11)
21 verbose stack     at process.kill (internal/process.js:190:13)
21 verbose stack     at process.listener (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:86:15)
21 verbose stack     at emitNone (events.js:91:20)
21 verbose stack     at process.emit (events.js:185:7)
21 verbose stack     at processEmit (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:146:32)
21 verbose stack     at processEmit (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:146:32)
21 verbose stack     at Signal.wrap.onsignal (internal/process.js:217:44)
22 verbose cwd C:\<path>\Workspace\Webstorm\<project>
23 error Windows_NT 6.3.9600
24 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ui5-codecompletion"
25 error node v6.11.2
26 error npm  v3.10.10
27 error code ENOSYS
28 error errno ENOSYS
29 error syscall kill
30 error kill ENOSYS
31 error If you need help, you may report this error at:
31 error     <https://github.com/npm/npm/issues>
32 verbose exit [ 1, true ]
```
Does that mean anything to you?

Thanks a lot!

**Comment by vobujs** [comment]
yep, this now clearly states a problem with node.
the log shows that you're still on node version 6.11.2 - I run the ```ui5-codecompletion``` Unit Tests with a minimum version of 6.11.4.
So please upgrade your local node installation to either the latest LTS version or even better the latest stable version over at https://nodejs.org/en/

**Comment by Raptor05** [comment]
Maybe that file is already from yesterday. I've today installed version 8.7.
The console shows:
```
C:\<path>\Workspace\Webstorm\<project>>node -v
v8.7.0
```
![image](https://user-images.githubusercontent.com/4174662/31929961-36477e64-b89e-11e7-9e40-c88fc5f4c98c.png)

And since the last try I've these two folders in my project folder:
![image](https://user-images.githubusercontent.com/4174662/31930014-7619e5b8-b89e-11e7-8f50-4c1071be46fd.png)

**Comment by vobujs** [comment]
so I booted up a VM w/ Win 10 only for you :)
and can confirm the bug you mentioned. Will try to take a look asap.
